name: CI Workflow  

on: push

jobs:
  print:
    runs-on: ubuntu-latest

    steps:
      - name : code Checkout repo
        uses: actions/checkout@v4

      - name : checking the code
        run : ls -l