name: Multiple Jobs Example

on:
  push:

jobs:
  job1: 
    runs-on: ubuntu-latest 
    
    steps: 
        - run: echo "This is Job 1" 
    
  job2: 
    runs-on: ubuntu-latest 
    needs: job1 
    steps: 
        - run: echo "This is Job 2"